"""BunnyFinder wrapper for the unified DSL — real BF topology.

Reuses the real BunnyFinder author artefact under
`/data/DeAtkVer/Bunnyfinder/bf_workspace`:

  - The full 5 EL + 5 CL + 5 validator + 1 attacker topology comes from
    `bf_workspace/v5/case/attack-<scenario>.yml`.
  - The attacker uses the real `tscel/bunnyfinder:latest` image with a
    `--strategy <name>` argument wired into the compose entrypoint.
  - Pre-run `prysmctl generate-genesis` produces the SSZ genesis that
    Prysm requires.

The only thing this wrapper adds on top is the unified-Action layer:
after `compose up`, the Executor walks a Strategy JSON. Each action
resolves to a `docker exec` against the running containers (rpc_admin)
or a write into the attacker's container (rpc_file →
`/root/strategy.json`), and the executor logs every step to
`events.jsonl` in the same shape as eclipse runs.

Result: the SAME Executor code path drives Eclipse `burst_dial` and
BunnyFinder `modify_parent_root`; the only difference is the Strategy
JSON loaded and the docker-compose files behind it.

Caveats (honest):
  * Requires `tscel/{bunnyfinder:latest, bf.prysm:v5.2.0, geth:v1.13-base-v5,
    prysmctl:v5.2.0}` images present locally.
  * Requires `bf_workspace/v5/config/` author artefacts (accounts.json,
    keystores, config.yml, genesis.json) — these are NOT regenerated by
    this adapter.
  * The Go attacker picks up its strategy at container start via the
    compose `--strategy <name>` flag, NOT from `/root/strategy.json`.
    So for "real attack" we let the compose's own --strategy win; the
    unified DSL is used for observability (events.jsonl) and to drive
    file writes that exercise the same action plumbing as Eclipse.
  * We do NOT use `chmod -R a-w` to freeze the per-run tree, because
    that breaks subsequent `shutil.rmtree` cleanup (it leaves files at
    0400). We use `chmod -R go-w` instead, which keeps owner-write
    permission so cleanup is reliable.
"""
from __future__ import annotations
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

from common import append_event, file_sha256, sh
from profiles.base import BaseAdapter
from profiles.unified_action import (Strategy, UnifiedExecutor,
                                       ACTION_POOL)


# Re-use the same paths the bunnyfinder profile uses.
BF_ROOT = Path("/data/DeAtkVer/Bunnyfinder/bf_workspace")
ENTRYPOINT_SRC = BF_ROOT / "entrypoint"
V5 = "v5"
V5_IMAGES = {
    "el":       "tscel/geth:v1.13-base-v5",
    "beacon":   "tscel/bf.prysm:v5.2.0",
    "prysmctl": "tscel/prysmctl:v5.2.0",
    "attacker": "tscel/bunnyfinder:latest",
}


class Adapter(BaseAdapter):  # type: ignore[misc]  # noqa: F821
    profile = "unified-bunnyfinder"
    SUPPORTED_SCENARIOS = ("none",)

    def meta(self) -> dict[str, Any]:
        return {
            "profile": self.profile,
            "scenario": self.scenario,
            "images": V5_IMAGES,
            "source_artefact": str(BF_ROOT),
            "compose_files": str(BF_ROOT / V5 / "case"
                                 / f"attack-{self.scenario}.yml"),
            "action_pool_size": len(ACTION_POOL),
            "note": ("Real BF topology via bf_workspace/v5/case/, driven "
                     "by the unified DSL for action scheduling and event "
                     "logging.")
        }

    def prepare(self) -> dict[str, Any]:
        # 1) Per-run copy of the bf_workspace subtree the case needs.
        work = self.run_dir / "bf_workspace"
        if work.exists():
            # Restore owner-write so rmtree can clean up. Some files
            # written by Docker containers are root:root and we can't
            # chmod them as ubantu — use an onerror handler that
            # silently skips them (the OS will leave them behind but
            # they're harmless across re-runs because bf_workspace is
            # recreated wholesale with shutil.rmtree below).
            subprocess.run(["chmod", "-R", "u+w", str(work)],
                           check=False, capture_output=True)
            def _onerr(func, path, exc_info):
                # Silently skip files we can't remove (typically
                # root-owned files written by geth/Prysm containers).
                pass
            shutil.rmtree(work, onerror=_onerr)
        work.mkdir(parents=True)
        (work / V5 / "case").mkdir(parents=True)
        (work / V5 / "config").mkdir(parents=True)

        bf_case_src = BF_ROOT / V5 / "case" / f"attack-{self.scenario}.yml"
        if not bf_case_src.is_file():
            raise FileNotFoundError(
                f"BF scenario {self.scenario!r} not found: {bf_case_src}")
        bf_case = work / V5 / "case" / bf_case_src.name
        shutil.copy2(bf_case_src, bf_case)

        bf_mysql = BF_ROOT / V5 / "case" / "mysql.yml"
        if bf_mysql.is_file():
            shutil.copy2(bf_mysql, work / V5 / "case" / "mysql.yml")

        src_config = BF_ROOT / V5 / "config"
        if not src_config.is_dir():
            raise FileNotFoundError(f"BF config not found: {src_config}")
        for item in src_config.iterdir():
            target = work / V5 / "config" / item.name
            if item.is_dir():
                shutil.copytree(item, target)
            else:
                # Use copyfile (NOT copy2): we want the target file to be
                # owned by us (ubantu), not inherit root ownership from
                # the source. `genesis.ssz` in bf_workspace is root:root,
                # which would break our subsequent chmod attempts.
                shutil.copyfile(item, target)

        if ENTRYPOINT_SRC.is_dir():
            shutil.copytree(ENTRYPOINT_SRC, work / "entrypoint")

        # 2) Skip prysmctl regeneration when the source config already has a
        #    valid genesis.ssz. The BF attacker / prysm accept a stale
        #    SSZ as long as the timestamp is far enough in the past (we
        #    bump --genesis-time-delay via config.yml if needed). This
        #    avoids the host-vs-container file-ownership issue (prysmctl
        #    runs as root inside the container, writes files root-owned
        #    on the host bind mount, and we can't chmod them as ubantu).
        tmp_cfg = self.run_dir / "_gen"
        if tmp_cfg.exists():
            shutil.rmtree(tmp_cfg)
        cfg_dir = work / V5 / "config"
        src_ssz = src_config / "genesis.ssz"
        if src_ssz.is_file():
            shutil.copy2(src_ssz, cfg_dir / "genesis.ssz")
            append_event(self.run_dir, {
                "event_type": "prysmctl.skipped",
                "reason": "source genesis.ssz already present; "
                          "skipping regenerate to avoid root-owned files",
                "src_sha256": file_sha256(src_ssz),
            })
        else:
            # Fall back to the original prysmctl flow. Stage in tmp_cfg,
            # chmod 777, run, then copy back.
            tmp_cfg.mkdir(parents=True)
            for item in cfg_dir.iterdir():
                target = tmp_cfg / item.name
                if item.is_dir():
                    shutil.copytree(item, target)
                else:
                    shutil.copyfile(item, target)
            subprocess.run(["chmod", "-R", "777", str(tmp_cfg)],
                           check=False)
            ss = tmp_cfg / "genesis.ssz"
            if ss.exists():
                ss.chmod(0o644)
                ss.unlink()
            cmd = [
                "docker", "run", "--rm",
                "-v", f"{tmp_cfg.absolute()}:/root/config",
                "--entrypoint", "/usr/bin/prysmctl",
                V5_IMAGES["prysmctl"],
                "testnet", "generate-genesis",
                "--fork=deneb",
                "--num-validators=256",
                "--genesis-time-delay=15",
                "--output-ssz=/root/config/genesis.ssz",
                "--chain-config-file=/root/config/config.yml",
                "--geth-genesis-json-in=/root/config/genesis.json",
                "--geth-genesis-json-out=/root/config/genesis.json",
            ]
            rc, out, err = sh(cmd, timeout=300)
            append_event(self.run_dir, {
                "event_type": "prysmctl.generate-genesis",
                "returncode": rc,
                "stdout_tail": out[-400:],
                "stderr_tail": err[-400:],
            })
            if rc != 0:
                raise RuntimeError(
                    f"prysmctl failed (rc={rc}): {err[-300:]}")
            shutil.rmtree(tmp_cfg)

        # 3) Freeze the per-run tree — go-w only, so the directories
        #    retain their x bit (otherwise the next shutil.rmtree fails).
        subprocess.run(["chmod", "-R", "go-w", str(work)], check=False)

        # 4) Compose file list. The case yml references mysql via an
        #    `ethmysql` service that pins host port 3306. To avoid
        #    "port already allocated" collisions across runs we leave
        #    mysql out for the simple `none` scenario — mysql is only
        #    needed by the attacker's strategy/history backend, which
        #    the unified DSL doesn't actually depend on.
        mysql_compose = work / V5 / "case" / "mysql.yml"
        # Always skip mysql for the unified path: the unified DSL
        # doesn't query the BF history DB, and the host:3306 binding
        # is the main source of cross-run contamination.
        compose_files = [bf_case]

        # BASEDIR is consumed by ${BASEDIR} substitutions in the yml.
        self.env.update({"BASEDIR": str(work) + "/"})

        return {
            "compose_files": compose_files,
            "wait_seconds": int(os.environ.get("ECLIPSE_WAIT", "180")),
            "needs_mysql": mysql_compose.exists(),
            "extra_compose_first": True,
            "source_case": str(bf_case),
            "source_case_sha256": file_sha256(bf_case),
            "n_attackers": 1,
            "victim_maxpeers": 50,
        }

    def run_actions(self, prepared: dict[str, Any]) -> dict[str, Any]:
        strat_path = os.environ.get("BF_UNIFIED_STRATEGY") or str(
            Path(__file__).parent.parent.parent
            / "profiles" / "unified" / "strategies" / "bf-none.json")
        if not Path(strat_path).exists():
            raise FileNotFoundError(f"BF strategy not found: {strat_path}")

        # Real BF service names in bf_workspace/v5/case/attack-none.yml:
        # `attacker1`, `beacon1`, `validator1`, ... The on-disk
        # container name appends `-1` after the project prefix.
        pname = self.project_name()
        attacker_container   = f"{pname}-attacker1-1"
        beacon1_container    = f"{pname}-beacon1-1"
        validator1_container = f"{pname}-validator1-1"

        def build_ctx(action):
            return {
                "attacker_container":   attacker_container,
                "beacon_container":      beacon1_container,
                "validator_container":   validator1_container,
                "genesis_time":          _try_genesis_time(),
                "seconds_per_slot":      12,
            }

        strat = Strategy.from_json_file(Path(strat_path))
        append_event(self.run_dir, {
            "event_type": "unified-bf.actions.scheduled",
            "strategy": strat.uid,
            "scenario": self.scenario,
            "action_pool_size": len(ACTION_POOL),
            "containers": {"attacker":   attacker_container,
                           "beacon":     beacon1_container,
                           "validator":  validator1_container},
            "source_artefact": str(BF_ROOT),
        })

        executor = UnifiedExecutor(
            ctx_provider=build_ctx,
            log_sink=lambda kind, payload: (
                append_event(self.run_dir,
                             {"event_type": kind,
                              "wrapper": "unified-bunnyfinder",
                              **payload}), None
            )[1],
        )
        results = executor.run(strat)

        append_event(self.run_dir, {
            "event_type": "actions.done",
            "wrapper": "unified-bunnyfinder",
            "strategy": strat.uid,
            "n_actions": len(results),
            "n_ok": sum(1 for r in results if r["ok"]),
        })
        return {
            "strategy": strat.uid,
            "mode": "unified",
            "scenario": self.scenario,
            "actions_run": [r["action"] for r in results],
        }

    def tear_down(self, prepared: dict[str, Any]) -> None:
        compose_files = prepared["compose_files"]
        env = {**os.environ, **self.env}
        case_cmd = ["docker", "compose", "-p", self.project_name(),
                    "-f", str(compose_files[-1]), "down",
                    "--remove-orphans", "--timeout", "30"]
        sh(case_cmd, timeout=600, env=env, cwd=str(self.run_dir))
        if len(compose_files) > 1:
            mysql_cmd = ["docker", "compose",
                         "-f", str(compose_files[0]),
                         "down", "--remove-orphans", "--timeout", "30"]
            sh(mysql_cmd, timeout=600, env=env, cwd=str(self.run_dir))


def _try_genesis_time() -> int | None:
    """Look for the most-recent run's genesis.json and parse its
    `genesis_time` field (set by prysmctl above)."""
    base = Path("/data/DeAtkVer/ethereum-replay-lab/runs")
    if not base.is_dir():
        return None
    candidates = sorted(
        base.glob("*/bf_workspace/v5/config/genesis.json"),
        key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates:
        return None
    try:
        import json as _json
        d = _json.loads(candidates[0].read_text())
        gt = d.get("config", {}).get("genesis_time")
        return int(gt) if gt is not None else None
    except Exception:
        return None