"""BunnyFinder wrapper for the unified DSL — smoke-test variant.

The full BunnyFinder artefact (`bf_workspace/v5/runtest.sh`) brings up
5 EL + 5 CL + 5 validator + 1 attacker containers with MySQL; that takes
~30 minutes to deploy. For the purpose of comparing execution flow
between eclipse and bunnyfinder actions, we bring up a *minimal* two-node
topology:

  - bf-attacker: ethereum/client-go:latest (NOT the real BF attacker
    image, which is private to Tsinghua-CEL). It exposes a dummy
    `/root/strategy.json` file that this wrapper can write to.
  - bf-beacon:  same image, simulates the beacon role.

The point is *not* to reproduce the real BF attack end-to-end — that's
already done by `bf_workspace`. The point is to prove that the unified
Action DSL can drive BF-shaped actions (`set_strategy`,
`modify_parent_root`, `delay_to_next_slot`, `store_signed_attest`) the
same way it drives Eclipse-shaped ones (`burst_dial`, `add_static_peer`,
`resolve_enode`), using the *same executor code path*.
"""
from __future__ import annotations
import os
import secrets
import shutil
import subprocess
from pathlib import Path
from typing import Any

from common import append_event, file_sha256, sh
from profiles.base import BaseAdapter
from profiles.unified_action import (Strategy, UnifiedExecutor,
                                       ACTION_POOL)


CHAIN_ID = 32391

# Role -> IP for our minimal 2-node topology.
ATTACKER_IP = "172.80.2.50"
BEACON_IP   = "172.80.2.20"
PORT        = 30303


def _write_script(path: Path, nodekey_hex: str, role: str) -> None:
    """Same shape as eclipse's attacker.sh — geth with admin RPC and
    P2P enabled, listening on PORT. We don't need a real CL — just a
    geth that can accept admin_addPeer and host a writable /root."""
    path.write_text(
        "#!/bin/sh\nset -eu\n"
        "geth init --datadir=/data /genesis.json\n"
        f"nohup geth --datadir=/data --networkid={CHAIN_ID} "
        f"--port={PORT} --nodekeyhex={nodekey_hex} "
        "--http --http.addr=0.0.0.0 --http.port=8545 "
        "--http.api=admin,eth,net,web3 --ipcdisable --nodiscover "
        "--maxpeers=50 > /data/geth.log 2>&1 &\n"
        "mkdir -p /root\n"
        "exec tail -F /data/geth.log\n"
    )
    path.chmod(0o755)


def _write_genesis(work: Path) -> Path:
    p = work / "genesis.json"
    p.write_text(
        '{"config":{"chainId":' + str(CHAIN_ID) + ','
        '"homesteadBlock":0,"eip150Block":0,"eip155Block":0,'
        '"eip158Block":0,"byzantiumBlock":0,"constantinopleBlock":0,'
        '"petersburgBlock":0,"istanbulBlock":0},'
        '"nonce":"0x0","timestamp":"0x0","extraData":"0x",'
        '"gasLimit":"0x1c9c380","difficulty":"0x1",'
        '"mixHash":"0x' + "0"*64 + '",'
        '"coinbase":"0x' + "0"*40 + '",'
        '"alloc":{},"number":"0x0","gasUsed":"0x0",'
        '"parentHash":"0x' + "0"*64 + '"}'
    )
    return p


class Adapter(BaseAdapter):
    profile = "unified-bunnyfinder"

    SUPPORTED_SCENARIOS = ("smoke",)

    def meta(self) -> dict[str, Any]:
        return {
            "profile": self.profile,
            "scenario": self.scenario,
            "chain_id": CHAIN_ID,
            "supported_scenarios": list(self.SUPPORTED_SCENARIOS),
            "action_pool_size": len(ACTION_POOL),
            "note": ("smoke-test only; full BF attack requires bf_workspace/"
                     "v5/runtest.sh with MySQL (out of scope here).")
        }

    def prepare(self) -> dict[str, Any]:
        work = self.run_dir / "unified-bf"
        if work.exists():
            shutil.rmtree(work)
        work.mkdir(parents=True)
        genesis = _write_genesis(work)

        # Two-node minimal topology: 1 attacker, 1 beacon.
        attacker_key = secrets.token_hex(32)
        beacon_key   = secrets.token_hex(32)
        _write_script(work / "attacker.sh", attacker_key, "attacker")
        _write_script(work / "beacon.sh",   beacon_key,   "beacon")
        (work / "attacker-data").mkdir()
        (work / "beacon-data").mkdir()

        compose_path = work / "docker-compose.yml"
        compose_path.write_text(self._compose(work, genesis))
        return {
            "compose_files": [compose_path],
            "wait_seconds": int(os.environ.get("ECLIPSE_WAIT", "60")),
            "needs_mysql": False,
            "extra_compose_first": False,
            "source_case": str(compose_path),
            "source_case_sha256": file_sha256(compose_path),
            "n_attackers": 1,
            "victim_maxpeers": 50,
        }

    def _compose(self, work: Path, genesis: Path) -> str:
        net = f"erl_ubf-{self.run_dir.name}"
        return f"""# Auto-generated by profiles/unified_bunnyfinder.py
# Minimal 2-node BF smoke test.
networks:
  {net}:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16

services:
  beacon:
    image: ethereum/client-go:latest
    entrypoint: ["/scripts/beacon.sh"]
    volumes:
      - {work.absolute()}/beacon.sh:/scripts/beacon.sh:ro
      - {work.absolute()}/beacon-data:/data
      - {genesis.absolute()}:/genesis.json:ro
    networks:
      {net}:
        ipv4_address: {BEACON_IP}

  attacker:
    image: ethereum/client-go:latest
    depends_on: [beacon]
    entrypoint: ["/scripts/attacker.sh"]
    volumes:
      - {work.absolute()}/attacker.sh:/scripts/attacker.sh:ro
      - {work.absolute()}/attacker-data:/data
      - {genesis.absolute()}:/genesis.json:ro
    networks:
      {net}:
        ipv4_address: {ATTACKER_IP}
"""

    def run_actions(self, prepared: dict[str, Any]) -> dict[str, Any]:
        rid = self.run_dir.name
        strat_path = os.environ.get("BF_UNIFIED_STRATEGY") or str(
            Path(__file__).parent.parent.parent
            / "profiles" / "unified" / "strategies" / "bf-smoke.json")
        if not Path(strat_path).exists():
            raise FileNotFoundError(f"BF strategy not found: {strat_path}")

        # Container names come from docker compose's project name, which
        # is self.project_name() (see BaseAdapter). Do NOT hardcode.
        pname = self.project_name()          # erl_unified-bunnyfinder-<run_id>
        attacker_container = f"{pname}-attacker-1"
        beacon_container   = f"{pname}-beacon-1"

        def build_ctx(action):
            # route BF actions to attacker container by default
            return {
                "attacker_container": attacker_container,
                "validator_container": attacker_container,
                "beacon_container":    beacon_container,
                "genesis_time":        None,    # no real chain clock
                "seconds_per_slot":    12,
            }

        strat = Strategy.from_json_file(Path(strat_path))
        append_event(self.run_dir, {
            "event_type": "unified-bf.actions.scheduled",
            "strategy": strat.uid,
            "scenario": self.scenario,
            "action_pool_size": len(ACTION_POOL),
            "containers": {"attacker": attacker_container,
                            "beacon": beacon_container},
        })

        executor = UnifiedExecutor(
            ctx_provider=build_ctx,
            log_sink=lambda kind, payload: (
                append_event(self.run_dir,
                             {"event_type": kind,
                              "wrapper": "unified-bunnyfinder",
                              **payload}), None
            )[1],
        )
        results = executor.run(strat)
        append_event(self.run_dir, {
            "event_type": "actions.done",
            "wrapper": "unified-bunnyfinder",
            "strategy": strat.uid,
            "n_actions": len(results),
            "n_ok": sum(1 for r in results if r["ok"]),
        })
        return {
            "strategy": strat.uid,
            "mode": "unified",
            "scenario": self.scenario,
            "actions_run": [r["action"] for r in results],
        }